#!/bin/sh /etc/rc.common

START=99
STOP=10
USE_PROCD=1

start_service() {
    procd_open_instance
    procd_set_param command /usr/bin/wan-watchdog.sh
    procd_set_param respawn 5 5 0
    procd_close_instance
}
